### ISSUE TITLE
Sorry I was MIA.

### ISSUE THREAD

**Issue by timkindberg** [jonasholtkamp/jest-when-xt#12]
So somehow I missed out on the various issues and pull requests on my project. I think it's awesome that you have extended it so much.

At this point, would it be worthwhile to do a large PR back to the original jest-when project or are you pretty set here at jest-when-xt?

If we were to get jest-when up-to-date what features would close the gap?

**Comment by timkindberg** [comment]
Ok I think I may do that. Thanks!

**Comment by wh1t3cAt1k** [comment]
Please clarify which library we should use now?

**Comment by jonasholtkamp** [comment]
That's up to you and the features you'd like to use.

**Comment by wh1t3cAt1k** [comment]
So the changes haven't been pulled back to the original repository? It would be nice to clarify somewhere the differences in functionality!

**Comment by timkindberg** [comment]
I have all of the changes they made back in my original repo. There has also been a lot of additional activity.

**Comment by wh1t3cAt1k** [comment]
Okay! Then, at this stage, I would propose to unite forces and just keep
one repository to avoid confusion. @jonasholtkamp what do you think?
